items:
  - lang: en
    mail: contact@lehub.ca
    homepage: /en/
    title: Climate Justice Organizing HUB
    langname: English
    footer_1: >-
      The HUB is a project of <br>

      <a target="_blank" href="https://www.smallchangefund.ca/">the Small Change Fund</a>


      * <a target="_blank" href="https://www.facebook.com/climatejusticeorganizingHUB">Facebook</a>

      * <a target="_blank" href="https://www.instagram.com/theclimatejusticeorganizinghub/">Instagram</a>
    footer_2: >
      The Climate Justice Organizing HUB is based on the territories of The
      Kanien’kehá:ka, who are the keepers of the Eastern Door of the
      Haudenosaunee Confederacy. The island called “Montreal” is known as
      Tiotia:ke in Kanien’kehá, a language of the Iroquoian family, and has
      historically been a meeting place for many Indigenous nations. <a
      target="_blank" href="https://www.youtube.com/watch?v=5Mm2vDSgXD0">Ellen
      Gabriel shares more perspective on this land acknowledgement here.</a>
  - lang: fr
    mail: info@lehub.ca
    homepage: /fr/
    title: HUB de mobilisation pour la justice climatique
    langname: Français
    footer_1: >-
      Le HUB est un projet du <br>

      <a target="_blank" href="https://www.smallchangefund.ca/">Small Change

      Fund</a>


      * <a target="_blank" href="https://www.facebook.com/LeHub.ca">Facebook</a>

      * <a target="_blank" href="https://www.instagram.com/lehub.ca/">Instagram</a>


      <br><br>


      ##### 

      Dans un désir d’inclusion et d’accessibilité au texte, ce dernier a été rédigé en utilisant la formulation neutre.
    footer_2: >-
      Le HUB de mobilisation pour la justice climatique a été fondé sur les
      territoires des Kanien’kehá:ka, qui sont les gardiens de la Porte de l’Est
      de la Confédération Haudenosaunee. L’île appelée “Montréal” est connue
      sous le nom de Tiotia:ke en Kanien’kehá, une langue de la famille
      iroquoienne, et a historiquement été un lieu de rencontre pour de
      nombreuses nations autochtones. <a target="_blank"
      href="https://www.youtube.com/watch?v=5Mm2vDSgXD0">Ellen

      Gabriel partage ici son point de vue sur cette

      reconnaissance territoriale.</a>
