items:
  - lang: en
    homepage: /en/
    title: Climate Justice Organizing Hub
    langname: English
  - lang: fr
    homepage: /fr/
    title: Hub de mobilisation pour la justice climatique
    langname: Français
