# config.yml

backend:
  # See https://www.netlifycms.org/docs/authentication-backends/#github-backend
  name: github
  repo: lehubca/lehub-website
  branch: master
  base_url: https://auth.static.dcycle.com
  auth_endpoint: auth/github/alberto56
media_folder: 'docs/media'
public_folder: "/media"
collections:
  - name: 'secondarypages'
    create: true
    label: 'Secondary Pages'
    folder: 'docs/_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'basic' }
      - { label: 'Title (for example "Trainings")', name: 'title1', widget: 'string' }
      - { label: 'Language ("fr" or "en")', name: 'lang', widget: 'string', default: 'en' }
      - { label: 'Path (for example /trainings/)', name: 'permalink', widget: 'string' }
      - { label: 'Path in other language (for example /formations/)', name: 'otherlang_url', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Français'
        name: 'francais'
        file: 'docs/index.html'
        fields:
          - { label: 'Image du haut', name: 'image_top', widget: 'image', required: false }
          - { label: 'Image du haut opacité, e.g. opacity: 0.5', name: 'image_top_css', widget: string, required: false }
          - { label: 'Layout', name: 'layout', widget: hidden }
          - { label: 'Titre complet', name: 'title', widget: string }
          - { label: 'Titre 1', name: 'title1', widget: string, required: false }
          - { label: 'Titre 2', name: 'title2', widget: string, required: false }
          - { label: 'Titre 3', name: 'title3', widget: string, required: false }
          - { label: 'Titre 4', name: 'title4', widget: string, required: false }
          - { label: 'Other Lang URL', name: 'otherlang_url', widget: hidden }
          - { label: 'Other Lang name', name: 'otherlang_name', widget: hidden }
          - { label: 'lang', name: 'lang', widget: hidden }
          - { label: 'footer', name: 'footer', widget: hidden }
          - { label: 'Corps', name: 'body', widget: 'markdown' }
      - label: 'English'
        name: 'english'
        file: 'docs/en/index.html'
        fields:
          - { label: 'Top image', name: 'image_top', widget: 'image', required: false }
          - { label: 'Top image css, e.g. opacity: 0.5', name: 'image_top_css', widget: string, required: false }
          - { label: 'Layout', name: 'layout', widget: hidden }
          - { label: 'Full title', name: 'title', widget: string }
          - { label: 'Title 1', name: 'title1', widget: string, required: false }
          - { label: 'Title 2', name: 'title2', widget: string, required: false }
          - { label: 'Title 3', name: 'title3', widget: string, required: false }
          - { label: 'Title 4', name: 'title4', widget: string, required: false }
          - { label: 'Other Lang URL', name: 'otherlang_url', widget: hidden }
          - { label: 'Other Lang name', name: 'otherlang_name', widget: hidden }
          - { label: 'lang', name: 'lang', widget: hidden }
          - { label: 'footer', name: 'footer', widget: hidden }
          - { label: 'Body', name: 'body', widget: 'markdown' }
